[project]
name = "mcp-clinet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.5.0",
    "openai>=1.68.2",
    "python-dotenv>=1.0.1",
]
